# Generated by Django 3.2 on 2021-08-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorderposition',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_positions', to='my_shop_app.order'),
        ),
        migrations.AlterField(
            model_name='productorderposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_shop_app.product'),
        ),
    ]
