# Generated by Django 3.2 on 2021-08-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop_app', '0003_alter_productorderposition_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость заказа'),
        ),
    ]
